Update spec.md
trustoverip/TechArch pull request #61
Opened 2022-11-06 18:33 UTC by andorsk

My initial run at editors section. To discuss later with tech arch team.

2022-11-06 18:36 UTC, andorsk commented
@talltree @wenjing any thoughts on this? I'll lean on your advice/wisdom here, as you guys have been on the project for a lot longer than I have, so your input will be really valuable to close this.

2022-11-13 18:19 UTC, talltree requested changes

2022-11-13 19:10 UTC, talltree approved these changes

2022-11-13 19:11 UTC, talltree commented
Merging as all editors are listed with affiliations (when applicable).

2022-11-13 19:12 UTC, merged